=== bmrobert/bmrobert.github.io/assets/schemas/BottleShots.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "dateCreated": {
        "type": "string"
      },
      "datePublished": {
        "type": "string"
      },
      "dateModified": {
        "type": "string"
      },
      "extension": {
        "type": "string"
      },
      "upc": {
        "type": "string"
      },
      "brandFamily": {
        "type": "string"
      },
      "varietal": {
        "type": "string"
      },
      "vintage": {
        "type": "string"
      },
      "itemSize": {
        "type": "string"
      },
      "webImage": {
        "type": "string"
      },
      "miniImage": {
        "type": "string"
      },
      "standardFinalJpeg": {
        "type": "string"
      },
      "thul": {
        "type": "string"
      },
      "transparentPNG": {
        "type": "string"
      }
    },
    "required": ["id", "name"]
  }
}

=== bmrobert/bmrobert.github.io/assets/examples/BottleShotExample.json
[
  {
    "brandFamily": "754",
    "dateCreated": "2017-01-05T21:10:18Z",
    "dateModified": "2017-01-06T16:24:26Z",
    "datePublished": "2016-12-16T18:12:09Z",
    "extension": "psd",
    "id": "9135BEC3-CF40-4819-B7C9C16DD7E92BF1",
    "itemSize": "219",
    "miniImage": "https://d3cy9zhslanhfa.cloudfront.net/media/final/5be7df2b-2a56-417f-84fe-dec1227f9116/mini-0AA4663D-852F-4DA2-97877C3DF1AD6BA7.png",
    "name": "2014 CHS Cabernet Sauvignon 750ml Bottle Shot",
    "standardFinalJpeg": "https://d3cy9zhslanhfa.cloudfront.net/media/final/5be7df2b-2a56-417f-84fe-dec1227f9116/Standard Final JPG-CHS_Bottle_Shot.jpg",
    "thul": "https://d3cy9zhslanhfa.cloudfront.net/media/final/5be7df2b-2a56-417f-84fe-dec1227f9116/thul-7ECA50DA-3BF8-4872-9BC1D6B268CFD9F2.png",
    "upc": "184745000126",
    "varietal": "198",
    "vintage": "2014",
    "webImage": "https://d3cy9zhslanhfa.cloudfront.net/media/final/5be7df2b-2a56-417f-84fe-dec1227f9116/webimage-4D27936B-F803-4DC7-80DB39A24800A652.png"
  }
]
