=== bmrobert/bmrobert.github.io/assets/schemas/Brand.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "properties": {
    "code": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "ownerCode": {
      "type": "string"
    },
    "ownerDescription": {
      "type": "string"
    },
    "familyCode": {
      "type": "string"
    },
    "familyDescription": {
      "type": "string"
    },
    "subBrands": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "subBrandCode": {
            "type": "string"
          },
          "subBrandDescription": {
            "type": "string"
          }
        },
        "required": [
          "subBrandCode"
        ],
        "minItems": 0
      }
    }
  },
  "required": [
    "code",
    "description",
    "ownerCode",
    "ownerDescription",
    "subBrands"
  ]
}

=== bmrobert/bmrobert.github.io/assets/examples/BrandExample.json
{
  "code": "137",
  "description": "BAROSSA VALLEY ESTATES",
  "familyCode": "135",
  "familyDescription": "BAROSSA VALLEY ESTATES",
  "ownerCode": "106",
  "ownerDescription": "OTHER",
  "subBrands": [
    {
      "subBrandCode": "1062",
      "subBrandDescription": "BAROSSA VALLEY ESTATE E MINOR"
    },
    {
      "subBrandCode": "1069",
      "subBrandDescription": "BAROSSA VALLEY ESTATES"
    }
  ]
}

=== bmrobert/bmrobert.github.io/assets/examples/BrandsExample.json
[
  {
    "code": "101",
    "description": "DAYS",
    "familyCode": "101",
    "familyDescription": "DAYS",
    "ownerCode": "100",
    "ownerDescription": "CONSTELLATION BRANDS US OPERATIONS, INC",
    "subBrands": [
      {
        "subBrandCode": "1001",
        "subBrandDescription": "77 DAYS"
      }
    ]
  },
  {
    "code": "101",
    "description": "DAYS",
    "familyCode": "101",
    "familyDescription": "DAYS",
    "ownerCode": "100",
    "ownerDescription": "CONSTELLATION BRANDS US OPERATIONS, INC",
    "subBrands": [
      {
        "subBrandCode": "2340",
        "subBrandDescription": "240 DAYS"
      }
    ]
  }
 ]
