=== bmrobert/bmrobert.github.io/assets/schemas/Items.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "universalSKUCode": {
        "type": "string"
      },
      "universalSKUDescription": {
        "type": "string"
      },
      "upc": {
        "type": "string"
      },
      "gtin": {
        "type": "string" 
      },
      "itemCode": {
        "type": "string"
      },
      "itemDescription": {
        "type": "string"
      },
      "beverageSegmentCode": {
        "type": "string"
      },
      "beverageSegmentDescription": {
        "type": "string"
      },
      "brandCode": {
        "type": "string"
      },
      "subBrandCode": {
        "type": "string"
      },
      "varietalBlendCode": {
        "type": "string"
      },
      "vintageDescription": {
        "type": "string"
      },
      "typeCode": {
        "type": "string"
      }
    },
    "required": ["id"]
  }
}

=== bmrobert/bmrobert.github.io/assets/examples/ItemsExample.json
[
  {
    "beverageSegmentCode": "100",
    "beverageSegmentDescription": "WINE",
    "brandCode": "110",
    "gtin": "063657001714",
    "id": "1000",
    "itemCode": "1",
    "itemDescription": "ALP WWN NIAP ICB 1/12",
    "subBrandCode": "1013",
    "typeCode": "102",
    "universalSKUCode": "21945",
    "universalSKUDescription": "ALPENWEISS WHITE WINE 1L",
    "upc": "63657001714",
    "varietalBlendCode": "826",
    "vintageDescription": "N/A"
  },
  {
    "beverageSegmentCode": "100",
    "beverageSegmentDescription": "WINE",
    "brandCode": "327",
    "gtin": "063657003602",
    "id": "1001",
    "itemCode": "10",
    "itemDescription": "HERM APRA ICB 750/12",
    "subBrandCode": "1376",
    "typeCode": "102",
    "universalSKUCode": "22894",
    "universalSKUDescription": "HERMIT APERA 750ML",
    "upc": "006365700360",
    "varietalBlendCode": "IH2",
    "vintageDescription": "N/A"
  },
  {
    "beverageSegmentCode": "100",
    "beverageSegmentDescription": "WINE",
    "brandCode": "343",
    "gtin": "620654020010",
    "id": "1002",
    "itemCode": "100",
    "itemDescription": "INNA EST RIES VQA 750/12",
    "subBrandCode": "2391",
    "typeCode": "102",
    "universalSKUCode": "23011",
    "universalSKUDescription": "INNISKILLIN NIAGARA EST COL RIESLING 750ML",
    "upc": "062065402001",
    "varietalBlendCode": "632",
    "vintageDescription": "N/A"
  },
  {
    "beverageSegmentCode": "999",
    "beverageSegmentDescription": "N/A",
    "brandCode": "303",
    "gtin": "N/A",
    "id": "1003",
    "itemCode": "1000",
    "itemDescription": "GROW SNA PEAR RFRSH",
    "subBrandCode": "1336",
    "typeCode": "UNK",
    "universalSKUCode": "99999",
    "universalSKUDescription": "N/A",
    "upc": "N/A",
    "varietalBlendCode": "559",
    "vintageDescription": "N/A"
  },
  {
    "beverageSegmentCode": "UNK",
    "beverageSegmentDescription": "UNKNOWN",
    "brandCode": "999",
    "gtin": "UNK",
    "id": "1004",
    "itemCode": "10000",
    "itemDescription": "LB VALPO",
    "subBrandCode": "1807",
    "typeCode": "UNK",
    "universalSKUCode": "UNK",
    "universalSKUDescription": "UNKNOWN",
    "varietalBlendCode": "760",
    "vintageDescription": "NON VINTAGE"
  },
  {
    "beverageSegmentCode": "100",
    "beverageSegmentDescription": "WINE",
    "brandCode": "560",
    "gtin": "UNK",
    "id": "1005",
    "itemCode": "100003",
    "itemDescription": "TAGN EST RIES CVL 750/12",
    "subBrandCode": "1828",
    "typeCode": "102",
    "universalSKUCode": "99998",
    "universalSKUDescription": "DISCONTINUED",
    "upc": "9311659000527",
    "varietalBlendCode": "632",
    "vintageDescription": "N/A"
  }

]
