=== bmrobert/bmrobert.github.io/assets/schemas/stores/store_performance.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "storeID": {
      "type": "string"
    },
    "summaryLevel": {
      "type": "string"
    },
    "summaryTypes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "summaryTimes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "summaryComparisons": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "summary": {
      "type": "object",
      "properties": {
        "patternProperties": {
          "^[a-zA-Z0-9]*$":{
          "type": "object",
          "properties": {
            "Depletion Points": {
              "type": "object",
              "properties": {
                "FYTD": {
                  "type": "integer"
                },
                "12 Months": {
                  "type": "integer"
                },
                "6 Months": {
                  "type": "integer"
                },
                "3 Months": {
                  "type": "integer"
                },
                "Year Ago": {
                  "type": "object",
                  "properties": {
                    "FYTD": {
                      "type": "integer"
                    },
                    "12 Months": {
                      "type": "integer"
                    },
                    "6 Months": {
                      "type": "integer"
                    },
                    "3 Months": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "FYTD",
                    "12 Months",
                    "6 Months",
                    "3 Months"
                  ]
                },
                "Similar Accounts": {
                  "type": "object",
                  "properties": {
                    "FYTD": {
                      "type": "number"
                    },
                    "12 Months": {
                      "type": "number"
                    },
                    "6 Months": {
                      "type": "number"
                    },
                    "3 Months": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "FYTD",
                    "12 Months",
                    "6 Months",
                    "3 Months"
                  ]
                }
              },
              "required": [
                "FYTD",
                "12 Months",
                "6 Months",
                "3 Months",
                "Year Ago",
                "Similar Accounts"
              ]
            },
            "Depletions": {
              "type": "object",
              "properties": {
                "FYTD": {
                  "type": "integer"
                },
                "12 Months": {
                  "type": "integer"
                },
                "6 Months": {
                  "type": "integer"
                },
                "3 Months": {
                  "type": "integer"
                },
                "Year Ago": {
                  "type": "object",
                  "properties": {
                    "FYTD": {
                      "type": "integer"
                    },
                    "12 Months": {
                      "type": "integer"
                    },
                    "6 Months": {
                      "type": "integer"
                    },
                    "3 Months": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "FYTD",
                    "12 Months",
                    "6 Months",
                    "3 Months"
                  ]
                },
                "Similar Accounts": {
                  "type": "object",
                  "properties": {
                    "FYTD": {
                      "type": "number"
                    },
                    "12 Months": {
                      "type": "number"
                    },
                    "6 Months": {
                      "type": "number"
                    },
                    "3 Months": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "FYTD",
                    "12 Months",
                    "6 Months",
                    "3 Months"
                  ]
                }
              },
              "required": [
                "FYTD",
                "12 Months",
                "6 Months",
                "3 Months",
                "Year Ago",
                "Similar Accounts"
              ]
            },
            "Points of Distribution": {
              "type": "object",
              "properties": {
                "FYTD": {
                  "type": "integer"
                },
                "12 Months": {
                  "type": "integer"
                },
                "6 Months": {
                  "type": "integer"
                },
                "3 Months": {
                  "type": "integer"
                },
                "Year Ago": {
                  "type": "object",
                  "properties": {
                    "FYTD": {
                      "type": "integer"
                    },
                    "12 Months": {
                      "type": "integer"
                    },
                    "6 Months": {
                      "type": "integer"
                    },
                    "3 Months": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "FYTD",
                    "12 Months",
                    "6 Months",
                    "3 Months"
                  ]
                },
                "Similar Accounts": {
                  "type": "object",
                  "properties": {
                    "FYTD": {
                      "type": "number"
                    },
                    "12 Months": {
                      "type": "number"
                    },
                    "6 Months": {
                      "type": "number"
                    },
                    "3 Months": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "FYTD",
                    "12 Months",
                    "6 Months",
                    "3 Months"
                  ]
                }
              },
              "required": [
                "FYTD",
                "12 Months",
                "6 Months",
                "3 Months",
                "Year Ago",
                "Similar Accounts"
              ]
            }
          },
          "required": [
            "Depletion Points",
            "Depletions",
            "Points of Distribution"
          ]
        }
       }
      }
    }
  },
  "required": [
    "storeID",
    "summaryLevel",
    "summaryTypes",
    "summaryTimes",
    "summaryComparisons",
    "summary"
  ]
}

=== bmrobert/bmrobert.github.io/assets/examples/stores/store_performance.json
{
  "storeID": "5110665",
  "summaryLevel": "Brand",
  "summaryTypes": [
    "Depletion Points",
    "Depletions",
    "Points of Distribution"
  ],
  "summaryTimes": [
    "FYTD",
    "12 Months",
    "6 Months",
    "3 Months"
  ],
  "summaryComparisons": [
    "Year Ago",
    "Similar Accounts"
  ],
  "summary": {
    "Diseno": {
      "Depletion Points": {
        "FYTD": 50,
        "12 Months": 120,
        "6 Months": 50,
        "3 Months": 0,
        "Year Ago": {
          "FYTD": 90,
          "12 Months": 160,
          "6 Months": 90,
          "3 Months": 40
        },
        "Similar Accounts": {
          "FYTD": 38.6527939,
          "12 Months": 83.1881256,
          "6 Months": 38.6527939,
          "3 Months": 14.3966284
        }
      },
      "Depletions": {
        "FYTD": 5,
        "12 Months": 12,
        "6 Months": 5,
        "3 Months": 0,
        "Year Ago": {
          "FYTD": 9,
          "12 Months": 16,
          "6 Months": 9,
          "3 Months": 4
        },
        "Similar Accounts": {
          "FYTD": 3.86527944,
          "12 Months": 8.31881237,
          "6 Months": 3.86527944,
          "3 Months": 1.43966281
        }
      },
      "Points of Distribution": {
        "FYTD": 1,
        "12 Months": 1,
        "6 Months": 1,
        "3 Months": 0,
        "Year Ago": {
          "FYTD": 1,
          "12 Months": 1,
          "6 Months": 1,
          "3 Months": 1
        },
        "Similar Accounts": {
          "FYTD": 0.489285707,
          "12 Months": 0.655357122,
          "6 Months": 0.489285707,
          "3 Months": 0.353571415
        }
      }
    },
    "Blackstone": {
      "Depletion Points": {
        "FYTD": 33,
        "12 Months": 33,
        "6 Months": 33,
        "3 Months": 0,
        "Year Ago": {
          "FYTD": 66,
          "12 Months": 66,
          "6 Months": 66,
          "3 Months": 33
        },
        "Similar Accounts": {
          "FYTD": 25.2510109,
          "12 Months": 61.2243729,
          "6 Months": 25.2510109,
          "3 Months": 10.5532789
        }
      },
      "Depletions": {
        "FYTD": 3,
        "12 Months": 3,
        "6 Months": 3,
        "3 Months": 0,
        "Year Ago": {
          "FYTD": 6,
          "12 Months": 6,
          "6 Months": 6,
          "3 Months": 3
        },
        "Similar Accounts": {
          "FYTD": 2.29554653,
          "12 Months": 5.56585217,
          "6 Months": 2.29554653,
          "3 Months": 0.959388971
        }
      },
      "Points of Distribution": {
        "FYTD": 1,
        "12 Months": 1,
        "6 Months": 1,
        "3 Months": 0,
        "Year Ago": {
          "FYTD": 2,
          "12 Months": 2,
          "6 Months": 2,
          "3 Months": 1
        },
        "Similar Accounts": {
          "FYTD": 0.582843721,
          "12 Months": 0.822561681,
          "6 Months": 0.582843721,
          "3 Months": 0.386603981
        }
      }
    },
    "Ravenswood": {
      "Depletion Points": {
        "FYTD": 22,
        "12 Months": 66,
        "6 Months": 22,
        "3 Months": 22,
        "Year Ago": {
          "FYTD": 44,
          "12 Months": 77,
          "6 Months": 44,
          "3 Months": 22
        },
        "Similar Accounts": {
          "FYTD": 24.2539368,
          "12 Months": 55.0694962,
          "6 Months": 24.2539368,
          "3 Months": 10.3232183
        }
      },
      "Depletions": {
        "FYTD": 2,
        "12 Months": 6,
        "6 Months": 2,
        "3 Months": 2,
        "Year Ago": {
          "FYTD": 4,
          "12 Months": 7,
          "6 Months": 4,
          "3 Months": 2
        },
        "Similar Accounts": {
          "FYTD": 2.09930944,
          "12 Months": 4.76051807,
          "6 Months": 2.09930944,
          "3 Months": 0.878259659
        }
      },
      "Points of Distribution": {
        "FYTD": 1,
        "12 Months": 1,
        "6 Months": 1,
        "3 Months": 1,
        "Year Ago": {
          "FYTD": 1,
          "12 Months": 1,
          "6 Months": 1,
          "3 Months": 1
        },
        "Similar Accounts": {
          "FYTD": 0.520718217,
          "12 Months": 0.773480654,
          "6 Months": 0.520718217,
          "3 Months": 0.361878455
        }
      }
    },
    "Cribari Dessert": {
      "Depletion Points": {
        "FYTD": 23.2220001,
        "12 Months": 46.4440002,
        "6 Months": 23.2220001,
        "3 Months": 17.7775993,
        "Year Ago": {
          "FYTD": 22.2220001,
          "12 Months": 49.888401,
          "6 Months": 22.2220001,
          "3 Months": 17.7775993
        },
        "Similar Accounts": {
          "FYTD": 6.05340338,
          "12 Months": 12.3627911,
          "6 Months": 6.05340338,
          "3 Months": 2.9102664
        }
      },
      "Depletions": {
        "FYTD": 23.2220001,
        "12 Months": 46.4440002,
        "6 Months": 23.2220001,
        "3 Months": 17.7775993,
        "Year Ago": {
          "FYTD": 22.2220001,
          "12 Months": 49.888401,
          "6 Months": 22.2220001,
          "3 Months": 17.7775993
        },
        "Similar Accounts": {
          "FYTD": 6.05340338,
          "12 Months": 12.3627911,
          "6 Months": 6.05340338,
          "3 Months": 2.9102664
        }
      },
      "Points of Distribution": {
        "FYTD": 3,
        "12 Months": 3,
        "6 Months": 3,
        "3 Months": 2,
        "Year Ago": {
          "FYTD": 2,
          "12 Months": 3,
          "6 Months": 2,
          "3 Months": 2
        },
        "Similar Accounts": {
          "FYTD": 0.748671234,
          "12 Months": 1.00683367,
          "6 Months": 0.748671234,
          "3 Months": 0.531511009
        }
      }
    },
    "Black Velvet": {
      "Depletion Points": {
        "FYTD": 1.38709998,
        "12 Months": 4.24109983,
        "6 Months": 1.38709998,
        "3 Months": 0.640200019,
        "Year Ago": {
          "FYTD": 0,
          "12 Months": 16.0506992,
          "6 Months": 0,
          "3 Months": 0
        },
        "Similar Accounts": {
          "FYTD": 2.93477631,
          "12 Months": 5.67218208,
          "6 Months": 2.93477631,
          "3 Months": 1.46665585
        }
      },
      "Depletions": {
        "FYTD": 0.213400006,
        "12 Months": 0.653500021,
        "6 Months": 0.213400006,
        "3 Months": 0.106700003,
        "Year Ago": {
          "FYTD": 0,
          "12 Months": 2.5401001,
          "6 Months": 0,
          "3 Months": 0
        },
        "Similar Accounts": {
          "FYTD": 0.477566987,
          "12 Months": 0.921921551,
          "6 Months": 0.477566987,
          "3 Months": 0.238029018
        }
      },
      "Points of Distribution": {
        "FYTD": 0,
        "12 Months": 0,
        "6 Months": 0,
        "3 Months": 0,
        "Year Ago": {
          "FYTD": 0,
          "12 Months": 1,
          "6 Months": 0,
          "3 Months": 0
        },
        "Similar Accounts": {
          "FYTD": 0.223934263,
          "12 Months": 0.334874153,
          "6 Months": 0.223934263,
          "3 Months": 0.136106834
        }
      }
    },
    "Hogue Cellars": {
      "Depletion Points": {
        "FYTD": 130,
        "12 Months": 286,
        "6 Months": 130,
        "3 Months": 65,
        "Year Ago": {
          "FYTD": 195,
          "12 Months": 325,
          "6 Months": 195,
          "3 Months": 130
        },
        "Similar Accounts": {
          "FYTD": 26.1547699,
          "12 Months": 57.9313469,
          "6 Months": 26.1547699,
          "3 Months": 12.4385853
        }
      },
      "Depletions": {
        "FYTD": 10,
        "12 Months": 22,
        "6 Months": 10,
        "3 Months": 5,
        "Year Ago": {
          "FYTD": 15,
          "12 Months": 25,
          "6 Months": 15,
          "3 Months": 10
        },
        "Similar Accounts": {
          "FYTD": 1.99292767,
          "12 Months": 4.3999505,
          "6 Months": 1.99292767,
          "3 Months": 0.949868441
        }
      },
      "Points of Distribution": {
        "FYTD": 1,
        "12 Months": 1,
        "6 Months": 1,
        "3 Months": 1,
        "Year Ago": {
          "FYTD": 1,
          "12 Months": 1,
          "6 Months": 1,
          "3 Months": 1
        },
        "Similar Accounts": {
          "FYTD": 0.480263144,
          "12 Months": 0.6875,
          "6 Months": 0.480263144,
          "3 Months": 0.361842096
        }
      }
    },
    "Toasted Head": {
      "Depletion Points": {
        "FYTD": 255,
        "12 Months": 493,
        "6 Months": 255,
        "3 Months": 85,
        "Year Ago": {
          "FYTD": 204,
          "12 Months": 442,
          "6 Months": 204,
          "3 Months": 85
        },
        "Similar Accounts": {
          "FYTD": 61.9161301,
          "12 Months": 124.84874,
          "6 Months": 61.9161301,
          "3 Months": 32.9534416
        }
      },
      "Depletions": {
        "FYTD": 15,
        "12 Months": 29,
        "6 Months": 15,
        "3 Months": 5,
        "Year Ago": {
          "FYTD": 12,
          "12 Months": 26,
          "6 Months": 12,
          "3 Months": 5
        },
        "Similar Accounts": {
          "FYTD": 3.64212537,
          "12 Months": 7.34404325,
          "6 Months": 3.64212537,
          "3 Months": 1.9384377
        }
      },
      "Points of Distribution": {
        "FYTD": 1,
        "12 Months": 1,
        "6 Months": 1,
        "3 Months": 1,
        "Year Ago": {
          "FYTD": 1,
          "12 Months": 1,
          "6 Months": 1,
          "3 Months": 1
        },
        "Similar Accounts": {
          "FYTD": 0.630136967,
          "12 Months": 0.794520557,
          "6 Months": 0.630136967,
          "3 Months": 0.510273993
        }
      }
    },
    "Vendange": {
      "Depletion Points": {
        "FYTD": 0,
        "12 Months": 45,
        "6 Months": 0,
        "3 Months": 0,
        "Year Ago": {
          "FYTD": 15,
