=== bmrobert/bmrobert.github.io/assets/schemas/distributors/beerDistributors.json
{
   "$schema": "http://json-schema.org/draft-04/schema#",
   "type": "array",
   "items": {
      "type": "object",
      "properties": {
         "tdlinx_number": {
            "type": "string"
         },
         "distributor_name": {
            "type": "string"
         },
         "distributor_number": {
            "type": "string"
         },
         "address": {
            "type": "string"
         },
         "city": {
            "type": "string"
         },
         "state": {
            "type": "string"
         },
         "postal_cd": {
            "type": "string"
         },
         "phone_no": {
            "type": "string"
         },
         "latitude": {
            "type": "number"
         },
         "longitude": {
            "type": "number"
         },
         "last_update": {
            "type": "integer"
         },
         "high_impact": {
            "type": "string"
         },
         "unsold_account": {
            "type": "string"
         },
         "premise_type": {
            "type": "string"
         },
         "trade_classification": {
            "type": "string"
         },
         "planning_group": {
            "type": "string"
         },
         "distributor_rank_beer": {
            "type": "object",
            "properties": {
               "total_sales_r365_ty": {
                  "type": "number"
               },
               "total_sales_r365_ly": {
                  "type": "number"
               },
               "volume_rank": {
                  "type": "integer"
               }
            },
            "required": [
               "total_sales_r365_ty",
               "total_sales_r365_ly",
               "volume_rank"
            ]
         }
      },
      "required": [
         "tdlinx_number",
         "distributor_name",
         "distributor_number",
         "address",
         "city",
         "state",
         "postal_cd",
         "phone_no",
         "latitude",
         "longitude",
         "last_update",
         "high_impact",
         "unsold_account",
         "premise_type",
         "trade_classification",
         "planning_group",
         "distributor_rank_beer"
      ]
   }
}

=== bmrobert/bmrobert.github.io/assets/examples/distributors/beerDistributors.json
[  
   {  
      "tdlinx_number":"2063528",
      "distributor_name":"PITTSFIELD RESTAURANT",
      "distributor_number":"UNKNOWN",
      "address":"55 E WASHINGTON ST",
      "city":"CHICAGO",
      "state":"IL",
      "postal_cd":"606022103",
      "phone_no":"3126411806",
      "latitude":41.8831,
      "longitude":-87.6259,
      "last_update":201512,
      "high_impact":"N",
      "unsold_account":"N",
      "premise_type":"ON PREMISE",
      "trade_classification":"CASUAL DINING",
      "planning_group":"REGIONAL",
      "distributor_rank_beer":{  
         "total_sales_r365_ty":234.56,
         "total_sales_r365_ly":63.74,
         "volume_rank":1
      }
   },
   {  
      "tdlinx_number":"3982460",
      "distributor_name":"TONI PATISSERIE & CAFE",
      "distributor_number":"UNKNOWN",
      "address":"65 E WASHINGTON ST",
      "city":"CHICAGO",
      "state":"IL",
      "postal_cd":"606022101",
      "phone_no":"UNK",
      "latitude":41.8831,
      "longitude":-87.6255,
      "last_update":201512,
      "high_impact":"N",
      "unsold_account":"N",
      "premise_type":"ON PREMISE",
      "trade_classification":"CASUAL DINING",
      "planning_group":"REGIONAL",
      "distributor_rank_beer":{  
         "total_sales_r365_ty":234.56,
         "total_sales_r365_ly":63.74,
         "volume_rank":1
      }
   }
]
