=== bmrobert/bmrobert.github.io/assets/schemas/distributors/distributor_packagePerformance.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "ID": {
      "type": "string"
    },
    "distributorName": {
      "type": "string"
    },
    "distributorCode": {
      "type": "string"
    },
    "packagePerformance": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "beerProducts": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "ID": {
                  "type": "string"
                },
                "brandName": {
                  "type": "string"
                },
                "brandCode": {
                  "type": "string"
                },
                "beerPackages": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "packageID": {
                        "type": "string"
                      },
                      "packageName": {
                        "type": "string"
                      },
                      "growthDsc": {
                        "type": "string"
                      },
                      "performance": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "type": "string"
                          },
                          "measures": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "timeframe": {
                                  "type": "string"
                                },
                                "current": {
                                  "type": "number"
                                },
                                "yearAgo": {
                                  "type": "number"
                                }
                              },
                              "required": [
                                "timeframe",
                                "yearAgo"
                              ]
                            }
                          },
                          "performanceComparisons": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "Ultimate Parent": {
                                  "type": "object",
                                  "properties": {
                                    "ID": {
                                      "type": "string"
                                    },
                                    "name": {
                                      "type": "string"
                                    },
                                    "averages": {
                                      "type": "array",
                                      "items": {
                                        "type": "object",
                                        "properties": {
                                          "timeframe": {
                                            "type": "string"
                                          },
                                          "current": {
                                            "type": "number"
                                          },
                                          "yearAgo": {
                                            "type": "number"
                                          }
                                        },
                                        "required": [
                                          "timeframe",
                                          "current",
                                          "yearAgo"
                                        ]
                                      }
                                    }
                                  },
                                  "required": [
                                    "ID",
                                    "name",
                                    "averages"
                                  ]
                                }
                              }
                            }
                          }
                        },
                        "required": [
                          "type",
                          "measures",
                          "performanceComparisons"
                        ]
                      }
                    },
                    "required": [
                      "packageID",
                      "packageName",
                      "growthDsc"
                    ]
                  }
                }
              },
              "required": [
                "ID",
                "brandName",
                "brandCode",
                "beerPackages"
              ]
            }
          }
        },
        "required": [
          "beerProducts"
        ]
      }
    }
  },
  "required": [
    "ID",
    "distributorName",
    "distributorCode",
    "packagePerformance"
  ]
}

=== bmrobert/bmrobert.github.io/assets/examples/distributors/distributor_packagePerformance.json
{
  "ID": "2225231",
  "distributorName": "CHICAGO BEV SYSTEMS - IL",
  "distributorCode": "2225231",
  "packagePerformance": [
    {
      "beerProducts": [
        {
          "ID": "678",
          "brandName": "VICTORIA",
          "brandCode": "678",
          "beerPackages": [
            {
              "packageID": "80014010",
              "packageName": "VICTORIA 6PK BT",
              "growthDsc": "ORGANIC",
              "performance": {
                "type": "Depletions",
                "measures": [
                  {
                    "timeframe": "CYTD",
                    "current": 2920,
                    "yearAgo": 2888
                  },
                  {
                    "timeframe": "365 Days",
                    "current": 4194,
                    "yearAgo": 4263
                  },
                  {
                    "timeframe": "90 Days",
                    "current": 1277,
                    "yearAgo": 874
                  },
                  {
                    "timeframe": "30 Days",
                    "current": 407,
                    "yearAgo": 551
                  }
                ],
                "performanceComparisons": [
                  {
                    "Ultimate Parent": {
                      "ID": "1205",
                      "name": "DMA:CHICAGO IL",
                      "averages": [
                        {
                          "timeframe": "CYTD",
                          "current": 1555.4839712289663,
                          "yearAgo": 1618.6923076923076
                        },
                        {
                          "timeframe": "365 Days",
                          "current": 2245.8878173828125,
                          "yearAgo": 2293.5384615384614
                        },
                        {
                          "timeframe": "90 Days",
                          "current": 660.073716383714,
                          "yearAgo": 635.9423076923077
                        },
                        {
                          "timeframe": "30 Days",
                          "current": 215,
                          "yearAgo": 249.30769230769232
                        }
                      ]
                    }
                  }
                ]
              }
            },
            {
              "packageID": "80024732",
              "packageName": "VICTORIA 12PK CAN",
              "growthDsc": "ORGANIC",
              "performance": {
                "type": "Depletions",
                "measures": [
                  {
                    "timeframe": "CYTD",
                    "current": 3593,
                    "yearAgo": 0
                  },
                  {
                    "timeframe": "365 Days",
                    "current": 3593,
                    "yearAgo": 0
                  },
                  {
                    "timeframe": "90 Days",
                    "current": 2233,
                    "yearAgo": 0
                  },
                  {
                    "timeframe": "30 Days",
                    "current": 1248,
                    "yearAgo": 0
                  }
                ],
                "performanceComparisons": [
                  {
                    "Ultimate Parent": {
                      "ID": "1205",
                      "name": "DMA:CHICAGO IL",
                      "averages": [
                        {
                          "timeframe": "CYTD",
                          "current": 2940.1923076923076,
                          "yearAgo": 0
                        },
                        {
                          "timeframe": "365 Days",
                          "current": 2940.1923076923076,
                          "yearAgo": 0
                        },
                        {
                          "timeframe": "90 Days",
                          "current": 1820.9615384615386,
                          "yearAgo": 0
                        },
                        {
                          "timeframe": "30 Days",
                          "current": 1254,
                          "yearAgo": 0
                        }
                      ]
                    }
                  }
                ]
              }
            },
            {
              "packageID": "80014009",
              "packageName": "VICTORIA 1/4 BL KEG",
              "growthDsc": "ORGANIC",
              "performance": {
                "type": "Depletions",
                "measures": [
                  {
                    "timeframe": "CYTD",
                    "current": 819.772217,
                    "yearAgo": 2035.64038
                  },
                  {
                    "timeframe": "365 Days",
                    "current": 1470.76379,
                    "yearAgo": 3037.96069
                  },
                  {
                    "timeframe": "90 Days",
                    "current": 303.109711,
                    "yearAgo": 644.102783
                  },
                  {
                    "timeframe": "30 Days",
                    "current": 144.666397,
                    "yearAgo": 175.664398
                  }
                ],
                "performanceComparisons": [
                  {
                    "Ultimate Parent": {
                      "ID": "1205",
                      "name": "DMA:CHICAGO IL",
                      "averages": [
                        {
                          "timeframe": "CYTD",
                          "current": 348.5752644777298,
                          "yearAgo": 570.39263381958
                        },
                        {
                          "timeframe": "365 Days",
                          "current": 567.6390933990479,
                          "yearAgo": 834.5781113147735
                        },
                        {
                          "timeframe": "90 Days",
                          "current": 129.16583042144777,
                          "yearAgo": 204.94179592132568
                        },
                        {
                          "timeframe": "30 Days",
                          "current": 44.77752900123596,
                          "yearAgo": 68.19911975860596
                        }
                      ]
                    }
                  }
                ]
              }
            },
            {
              "packageID": "80013994",
              "packageName": "VICTORIA 24PK BT",
              "growthDsc": "ORGANIC",
              "performance": {
                "type": "Depletions",
                "measures": [
                  {
                    "timeframe": "CYTD",
                    "current": 2270,
                    "yearAgo": 2151
                  },
                  {
                    "timeframe": "365 Days",
                    "current": 3149,
                    "yearAgo": 3408
                  },
                  {
                    "timeframe": "90 Days",
                    "current": 942,
                    "yearAgo": 892
                  },
                  {
                    "timeframe": "30 Days",
                    "current": 316,
                    "yearAgo": 238
                  }
                ],
                "performanceComparisons": [
                  {
                    "Ultimate Parent": {
                      "ID": "1205",
                      "name": "DMA:CHICAGO IL",
                      "averages": [
                        {
                          "timeframe": "CYTD",
                          "current": 1713.6,
                          "yearAgo": 1983.2
                        },
                        {
                          "timeframe": "365 Days",
                          "current": 2525,
                          "yearAgo": 3007.5
                        },
                        {
                          "timeframe": "90 Days",
                          "current": 738.9,
                          "yearAgo": 851
                        },
                        {
                          "timeframe": "30 Days",
                          "current": 207.4,
                          "yearAgo": 242.1
                        }
                      ]
                    }
                  }
                ]
              }
            },
            {
              "packageID": "80014011",
              "packageName": "VICTORIA 12PK BT",
              "growthDsc": "ORGANIC",
              "performance": {
                "type": "Depletions",
                "measures": [
                  {
                    "timeframe": "CYTD",
                    "current": 5785,
                    "yearAgo": 6311
                  },
                  {
                    "timeframe": "365 Days",
                    "current": 8187,
                    "yearAgo": 9253
                  },
                  {
                    "timeframe": "90 Days",
                    "current": 2575,
                    "yearAgo": 2719
                  },
                  {
                    "timeframe": "30 Days",
                    "current": 913,
                    "yearAgo": 630
                  }
                ],
                "performanceComparisons": [
                  {
                    "Ultimate Parent": {
                      "ID": "1205",
                      "name": "DMA:CHICAGO IL",
                      "averages": [
                        {
                          "timeframe": "CYTD",
                          "current": 5906.807692307692,
                          "yearAgo": 5514.0192307692305
                        },
                        {
                          "timeframe": "365 Days",
                          "current": 8626.76923076923,
                          "yearAgo": 8066.384615384615
                        },
